# Config file for https://github.com/igorshubovych/markdownlint-cli

# MD007/ul-indent - Unordered list indentation
MD007:
    # Whether to indent the first level of the list
    start_indented: false
    # By how many spaces every next level must be indented. The default of 2 is not compatible with mkdocs!
    indent: 4

# MD009/no-trailing-spaces - Trailing spaces
MD009: false

# MD012/no-multiple-blanks - Multiple consecutive blank lines
MD012: false

# MD013/line-length - Line length
MD013:
    line_length: 120
    heading_line_length: 120
    code_block_line_length: 120
    # Include code blocks
    code_blocks: true
    # Include tables
    tables: false
    # Include headings
    headings: true
    # Strict length checking
    strict: false
    # Stern length checking
    stern: false

# MD025/single-title - Multiple top level headers in the same document
MD024:
    siblings_only: true

# MD045/no-alt-text - Images should have alternate text (alt text)
MD045: false

# MD046/code-block-style - Code block style (conflicts with admonitions)
MD046: false
# MD059/desriptive-link-text - Link text should be descriptive
MD059: false
