site_name: DSP-META

nav:
    - DSP-META: index.md
    - Metadata:
          - Metadata API: data/api.md
          - Data Model v1: data/v1-datamodel.md
          - Data Model v2: data/v2-datamodel.md
          - Adding Metadata: data/adding-metadata.md
    - Code Documentation:
          - Overview: code/overview.md
          - Front End: code/front-end.md
          - Back End: code/back-end.md
          - Observability & Tracing: code/observability.md

plugins:
    - include-markdown
    - search
    - git-revision-date-localized
    - neoteroi.mkdocsoad:
          use_pymdownx: true

theme:
    name: material
    logo: "https://raw.githubusercontent.com/dasch-swiss/dsp-docs/main/docs/assets/images/logo_bw.svg"
    favicon: "https://raw.githubusercontent.com/dasch-swiss/dsp-docs/main/docs/assets/images/logo_bw.svg"
    palette:
        - scheme: default
          toggle:
              icon: material/brightness-7
              name: Switch to dark mode
        - scheme: slate
          toggle:
              icon: material/brightness-4
              name: Switch to light mode
    features:
        - search.suggest
        # - navigation.tabs
        # - navigation.sections

markdown_extensions:
    - admonition
    - pymdownx.details
    - pymdownx.superfences
    - pymdownx.superfences:
          custom_fences:
              - name: mermaid
                class: mermaid
                format: !!python/name:pymdownx.superfences.fence_code_format
    - pymdownx.tasklist:
          custom_checkbox: true
    - pymdownx.tabbed:
          alternate_style: true

extra_css:
    - assets/css/mkdocsoad-v1.0.2.css
    - assets/css/theme.css
