name: PR Title

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  test:
    name: Check PR Title
    runs-on: ubuntu-latest
    steps:
      - uses: deepakputhraya/action-pr-title@master
        with:
          regex: '^(build|chore|data|docs|feat|fix|refactor|test|style)(\(.+\))?!?: .+$'
          max_length: 140
